Fix linter error
coderacheal/Hello_Microverse pull request #2
Opened 2022-11-30 23:01 UTC by coderacheal

Linter CSS indentation error

2022-11-30 23:38 UTC, rskinnerc requested changes
Hi @coderacheal 👋👋👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![giphy](https://user-images.githubusercontent.com/26911718/204931165-e421bd5a-fcc2-47a6-aee4-3fe69034ffbc.gif)


## Highlights 🎉🎉🎉
- Nice usage of GitHub flow
- Good job adding the big `node_modules` folder to `.gitignore`
- Well done applying the styles and linking to the CSS file 👌

## Required Changes ♻️
_Check the comments under the review._

- [ ] Remember that the pull request (PR) title should be a sentence describing what is the PR about. Please update it accordingly (i.e. `initial-project-setup`)
- [ ] The PR description (summary) should be a brief but more detailed summary of the changes you introduced. Please update the summary accordingly.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-30 23:38 UTC, rskinnerc commented on .gitignore
> +package-lock.json
♻️ Good job implementing a `.gitignore` file. However, please note that the package.json and package-lock.json files are not intended to be ignored. They describe the dependencies/packages your project uses so it can be used anywhere else. (by running `npm install`) 

- [ ] Please remove hose files from `.gitignore` 🤖

2022-11-30 23:38 UTC, rskinnerc commented on README.md
> +- [📝 License](#license)
♻️ Great! You are using the recommended template. However, the only optional section is the FAQ. You could keep the headings o all sections.

- [ ] Please keep the recommended sections. The only optional one is FAQ

2022-11-30 23:38 UTC, rskinnerc commented on README.md
> +Html is amarkup language and CSS is a styling language for HTML pages
♻️ Nice work describing the technologies you are using. Please note that double-checking for typos or grammar errors would help make your repo more professional. 👔👔

- [ ] Please fix the typos here. Also, consider using a list where each bullet point is a technology/framework

2022-11-30 23:38 UTC, rskinnerc commented on README.md
> +  git clone git@github.com:myaccount/my-project.git
♻️ Great! You are listing some steps the user should follow in order to run your project. There are some ways to make it look even more readable 🤓🤓:

- [ ] Please use `code block` when directing a command to run
- [ ] Kindly elaborate a little bit more on how to _initialize npm_. Perhaps indicating something like _Install linters and other dependencies with `npm install`_

2022-11-30 23:38 UTC, rskinnerc commented on index.html
> +    <title>Document</title>
[OPTIONAL] I suggest adding a more meaningful and custom title to your project. Making this a habit would make you a better dev. 😋

2022-11-30 23:38 UTC, rskinnerc commented on .gitignore
> +test.md
♻️ Great job adding the `test.md` file to `.gitignore` 👌. However, the file is still present.

- [ ] Please make sure that even though the file is listed on the `.gitignore`, it is not tracked by git. You might need to make use of the `git rm` command along with the `--cache` option. Take a look at [this link](https://git-scm.com/docs/git-rm) to understand how to remove a file from the index.

2022-12-01 00:37 UTC, coderacheal commented on .gitignore
> +package-lock.json
@rskinnerc I have done this. All required changes have been made.

2022-12-01 00:37 UTC, coderacheal commented on README.md
> +- [📝 License](#license)
@rskinnerc I didn't add those sections because I didn't know what to do there. I will try and implement your suggestion in my next project

2022-12-01 00:38 UTC, coderacheal commented on README.md
> +Html is amarkup language and CSS is a styling language for HTML pages
@rskinnerc Done. Thanks for catching that.

2022-12-01 00:40 UTC, coderacheal commented on index.html
> +    <title>Document</title>
@rskinnerc Done. I wasn't sure if it was allowed because I didn't see it in the instructions

2022-12-01 00:41 UTC, coderacheal commented on README.md
> +  git clone git@github.com:myaccount/my-project.git
I will try and implement your suggestions on the read me in my next project or over the weekend when I go over all the materials if that is okay with you

2022-12-01 01:14 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: 

Hi @coderacheal , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media.giphy.com/media/cYaB1VycDbOyOiXcCx/giphy.gif">

 ## Highlights
-  Linters are passing :+1: 
- Project is working well :+1: 
- Good use of Github flow :+1: 
- Meaningful commit messages :+1: 

 ## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 01:14 UTC, GedeonTS commented on .gitignore
> +test.md
-  [ ] Good job putting the `test.md` file inside the `.gitignore` :clap: , However, the file is still present in the repo , as recommended by the previous reviewer, I suggest you to remove it manualy from github or use any other way that suits you  to make sure git ignores it :+1:

2022-12-01 08:41 UTC, mckent05 approved these changes
Hi @coderacheal,

# STATUS : APPROVED ✔️ ✔️  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and good job! 🎉
![approved](https://user-images.githubusercontent.com/73607512/205006071-41ac8f21-6bbf-4e9e-9951-6b3460c6df9b.gif)
 

## Highlights
- All linter checks are passing ✔️ 
- PR is professional 👏 
- You have used the right Workflow for this milestone 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 08:54 UTC, merged